# Train:
#   python train.py --config configs/train.yaml dataset=ref_avs model=audio_mamba writer.run_name=audio_mamba dataset.params.data_root=REFAVS
# Inference:
#   python inference.py --config configs/inference.yaml dataset=ref_avs model=audio_mamba inferencer.from_pretrained=checkpoints/audio_mamba/model_best.pth dataset.params.data_root=REFAVS

model:
  _target_: models.audio_mamba.AudioMambaModel

  d_model: 768
  n_audio_layers: 2
  n_fusion_layers: 2
  d_state: 16
  conv_kernel: 4
  expand: 2
  ff_mult: 4
  dropout: 0.1

  audio_dim: 128
  text_dim: 768
  max_audio_tokens: 10
  max_text_tokens: 25

  mask_size: 256
  image_size: 256

  pretrained_visual_model: facebook/mask2former-swin-base-ade-semantic
  freeze_visual_backbone: true
  use_official_mamba_ssm: true
  hf_pretrained_mamba_model: state-spaces/mamba-130m-hf
  pretrained_mamba_path: null
  pretrained_mamba_prefix: ""
  freeze_mamba: false
