# Train:
#   python train.py --config configs/train.yaml dataset=ref_avs model=ref_avs_baseline writer.run_name=ref_avs_baseline dataset.params.data_root=REFAVS
# Inference:
#   python inference.py --config configs/inference.yaml dataset=ref_avs model=ref_avs_baseline inferencer.from_pretrained=checkpoints/ref_avs_baseline/model_best.pth dataset.params.data_root=REFAVS

model:
  _target_: models.ref_avs_baseline.RefAVSBaselineModel

  pretrained_m2f: facebook/mask2former-swin-base-ade-semantic

  dim_v: 1024

  num_heads: 8
  prompt_dim: 256
  cache_mem_beta: 1.0

  audio_dim: 128
  text_dim: 768

  mask_size: 256
  image_size: 256

  freeze_backbone: true
