model:
  _target_: models.ref_avs_baseline.RefAVSBaselineModel

  pretrained_m2f: facebook/mask2former-swin-base-ade-semantic

  dim_v: 1024

  num_heads: 8
  prompt_dim: 256
  cache_mem_beta: 1.0

  audio_dim: 128
  text_dim: 768

  mask_size: 256
  image_size: 256

  freeze_backbone: true
