dataset:
  module: advance
  name: ADVANCEDataset
  batch_size: 16
  eval_batch_size: 64
  num_workers: 2
  timeout: 120
  pin_memory: false
  params:
    vision_root: /content/drive/MyDrive/zenodo_dataset/ADVANCE_vision
    audio_root: /content/drive/MyDrive/zenodo_dataset/ADVANCE_sound
    sample_rate: 16000
    n_mels: 128
    max_audio_seconds: 5.0
    image_size: 224
    val_ratio: 0.1
    test_ratio: 0.1
    split_seed: 42
    use_cache: true
    prepare_cache_if_missing: true
    rebuild_cache: false
    cache_root: /content/drive/MyDrive/zenodo_dataset/ADVANCE_cache
    cache_prefix: advance_cache

inferencer:
  device_tensors: ["video", "audio", "question", "label"]
  save_path: advance_inference
  from_pretrained: checkpoints/advance_baseline/model_best.pth

metrics:
  inference:
    - _target_: metrics.simple_metrics.AccuracyMetric
      name: accuracy
    - _target_: metrics.simple_metrics.TopKAccuracyMetric
      k: 3
      name: top3_accuracy
    - _target_: metrics.simple_metrics.MacroPrecisionMetric
      name: macro_precision
    - _target_: metrics.simple_metrics.MacroRecallMetric
      name: macro_recall
    - _target_: metrics.simple_metrics.MacroF1Metric
      name: macro_f1
    - _target_: metrics.simple_metrics.BalancedAccuracyMetric
      name: balanced_accuracy
