defaults:
  - dataset: advance
  - model: advance_baseline
  - _self_

inferencer:
  seed: 42
  device: auto
  save_path: inference_outputs
  from_pretrained: checkpoints/advance_baseline/model_best.pth
  device_tensors: ["video", "audio", "question", "label"]

metrics:
  inference:
    - _target_: metrics.simple_metrics.AccuracyMetric
      name: accuracy
