defaults:
  - dataset: advance
  - model: advance_baseline
  - _self_

trainer:
  seed: 42
  device: auto
  n_epochs: 20
  save_dir: checkpoints
  save_period: 1
  monitor: "max val_accuracy"
  early_stop: 10
  max_grad_norm: 1.0
  skip_oom: true
  save_last: true
  device_tensors: ["video", "audio", "question", "label"]
  resume_from: null
  from_pretrained: null
  epoch_len: null
  log_step: 50

writer:
  _target_: writer.simple_writer.SimpleWriter
  run_name: train_run
  log_checkpoints: false
  loss_names: ["loss"]

loss_function:
  _target_: losses.cross_entropy.CrossEntropyLossWrapper

metrics:
  train:
    - _target_: metrics.simple_metrics.AccuracyMetric
      name: accuracy
  inference:
    - _target_: metrics.simple_metrics.AccuracyMetric
      name: accuracy

optimizer:
  _target_: torch.optim.AdamW
  lr: 3.0e-4
  weight_decay: 1.0e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 10
  gamma: 0.5
